#!/bin/sh

#   WARNING   this file is automatically generated by RT-Druid

#   If you want modify this file, you should move it to a safe folder,
#   like the project's root, and update the path inside the project 
#   properties "C/C++ Make Project" -> "Build command"
#   i.e.   ${workspace_loc:DashBoard---Design-of-Embedded-System}/make_launcher.bat


ERIKA_FILES=/home/evidence/Erika_SVN/
export ERIKA_FILES

make $@
